\
AZURE_OPENAI_TEXT_ENDPOINT=https://ai-satyamss2197024ai511680019271.openai.azure.com/
AZURE_OPENAI_TEXT_KEY=3K0lCByFz8rtuLuDRuSK6mAGQk0ySRFRKMxQ1RQjp6t9OrxyB5mkJQQJ99BEACHYHv6XJ3w3AAAAACOGyF0C
AZURE_OPENAI_IMAGE_ENDPOINT=https://satya-mcr9l71d-swedencentral.openai.azure.com/
AZURE_OPENAI_IMAGE_KEY=2weolebzkqDIUSaEX7l5EE32sFlGmaOr0DC4BDzmINRCpaZvTI2hJQQJ99BGACfhMk5XJ3w3AAAAACOGF45A
TWITTER_API_KEY = eTXcB6ZnUmu4LzdxcoRCGhwHn
TWITTER_API_SECRET = frauTlcNGjrXB1mQO43L9KFRRl1Mjfg8CURJsPgVBcWr9lVFMZ
TWITTER_ACCESS_TOKEN = 1526507663928205313-R4q0bGocGqvWwvTs0CgWJyieifSsZ0
TWITTER_ACCESS_SECRET = 0LngoeWLdyIPvDkuDAA11wAxGqpdTAKRTXFXi1qqZvndo
REDDIT_CLIENT_ID= 3gjGh_raF9VgpthurlAUDw
REDDIT_CLIENT_SECRET = ABXEZN4d98UtQBHoq_wk16rS2w
REDDIT_USER_AGENT=script:socialmanager:v1.0 (by /u/Low_Jump3665)