# Example Streamlit secrets template
AZURE_OPENAI_TEXT_ENDPOINT=https://your-text-endpoint.openai.azure.com/
AZURE_OPENAI_TEXT_KEY=your-text-key
AZURE_OPENAI_IMAGE_ENDPOINT=https://your-image-endpoint.openai.azure.com/
AZURE_OPENAI_IMAGE_KEY=your-image-key
AZURE_AI_FOUNDRY_ENDPOINT=https://your-ai-foundry-endpoint.azure.com/
AZURE_AI_FOUNDRY_API_KEY=your-ai-foundry-api-key
REDDIT_CLIENT_ID=your_reddit_client_id
REDDIT_CLIENT_SECRET=your_reddit_client_secret
REDDIT_USER_AGENT=script:socialmanager:v1.0 (by /u/yourusername) 